name: Build instantsccs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Default version of Node.js for jobs
  node-version: "14"

jobs:
  build-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:

    # Checkout source code
    - name: Checkout
      uses: actions/checkout@v3
    
    # Setup Nodejs
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
    
    # Setup Yarn
    - name: Install yarn
      run: npm install -g yarn

    # Install dependencies
    - name: Install build dependencies      
      run: yarn install --frozen-lockfile

    # Build script
    - run: |
        yarn build
        mkdir BUILD
        cp -r KoLmafia/scripts BUILD/scripts
        cp -r KoLmafia/dependencies.txt BUILD/dependencies.txt 

    # Synchronise & push BUILD directory to release branch     
    - name: Configure Git information
      run: |
        git config --global user.name "Build Script"
        git config --global user.email "<>"          


    - name: Synchronize & push into release branch
      run: |        
        git fetch --all
        echo "Switching into release"
        git stash && git drop stash
        git switch release        
        
        # Push build into the release branch                        
        mv BUILD/scripts scripts
        mv BUILD/dependencies.txt dependencies.txt
        git add scripts
        git add dependencies.txt
        git commit -m "Automated build"
        git push -f origin release        
