name: Build instantsccs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Default version of Node.js for jobs
  node-version: "12"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: ls
      - run: |
          git config user.name "Build Script"
          git config user.email "<>"
          echo "export const lastCommitHash: string | undefined = \"$(git rev-parse --short HEAD)\";" > src/_git_commit.ts
      - run: |
          git fetch --all               
          git switch release
          ls
          rm -rf scripts/                
          mv KoLmafia/* ./
          rm -rf KoLmafia
      - run: |
          git add scripts/  
          git add dependencies.txt                 
          git commit -m "Build Mafia files for commit $SHA"
          git push origin release
